services:
  mysql_db: ##service name
    image: mysql:latest
    container_name: ecommerce_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    ports:
      - "3336:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring_app:
    build: .
    container_name: ecommerce_api
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://ecommerce_db:3306/ecommerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on: ##depend on service
      - mysql_db
    ports:
      - "8080:8080"

volumes:
  mysql_data:
